# Generated by Django 4.1 on 2022-10-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('sana', models.DateField()),
                ('batafsil', models.TextField()),
                ('holat', models.CharField(max_length=20)),
            ],
        ),
    ]
