# Generated by Django 4.1 on 2022-10-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_alter_reja_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reja',
            old_name='user',
            new_name='student',
        ),
    ]
